# Generated by Django 4.2 on 2023-06-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.TextField(verbose_name='Название локации')),
                ('location_number', models.TextField(verbose_name='Номер локации')),
                ('next_location_latitude', models.TextField(verbose_name='Широта локации')),
                ('next_location_longitude', models.TextField(verbose_name='Долгота локации')),
                ('main_text', models.TextField(verbose_name='Главное описание локации')),
                ('detailed_description', models.TextField(verbose_name='Подробное описание локации')),
                ('audio_guide_text', models.TextField(verbose_name='Описание к голосовому')),
                ('audio_guide', models.FileField(upload_to='audio/', verbose_name='Голосовое сообщение')),
                ('additionally', models.TextField(verbose_name='Дополнительный текст локации')),
                ('additionally_button', models.TextField(verbose_name='Название дополнительной кнопки')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название кнопки')),
                ('image_description', models.TextField(blank=True, verbose_name='Название кнопки')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение для локации')),
                ('location_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Локация к которой привязано изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
