# Generated by Django 4.2 on 2023-06-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_image_image_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.IntegerField(verbose_name='Название кнопки'),
        ),
        migrations.AlterField(
            model_name='location',
            name='audio_guide_text',
            field=models.TextField(blank=True, verbose_name='Описание к голосовому'),
        ),
    ]
