# Generated by Django 4.2 on 2023-06-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_image_name_alter_location_audio_guide_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.IntegerField(choices=[(1, 'Я на месте'), (2, 'Подробное описание'), (3, 'Дополнительно')], verbose_name='Название кнопки'),
        ),
    ]
