# Generated by Django 4.2 on 2023-06-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.TextField(choices=[('Я на месте', 'Я на месте'), ('Подробное описание', 'Подробное описание'), ('Дополнительно', 'Дополнительно')], default='Я на месте', verbose_name='Название кнопки'),
        ),
    ]
