# Generated by Django 4.2 on 2023-06-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location_number',
            field=models.IntegerField(default=0, verbose_name='Номер локации'),
        ),
    ]
