# Generated by Django 4.2 on 2023-06-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_image_location_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='next_button_text',
            field=models.TextField(default='', verbose_name='Текст для кнопки "Дальше"'),
        ),
    ]
