# Generated by Django 4.2 on 2023-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_user_alter_location_next_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.TextField(blank=True, verbose_name='Имя пользователя при наличии'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, verbose_name='Юзернейм пользователя при наличии'),
        ),
    ]
