# Generated by Django 4.2 on 2023-06-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_user_full_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя пользователя при наличии'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, null=True, verbose_name='Юзернейм пользователя при наличии'),
        ),
    ]
